#!/usr/bin/env python3
"""Generate Swift definitions from the canonical repository theme manifest."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[3]
data = json.loads((ROOT / 'docs/themes.json').read_text())
def literal(value):
    if isinstance(value, bool): return str(value).lower()
    if isinstance(value, str): return json.dumps(value)
    return str(value)
def dictionary(value):
    return '[' + ', '.join(f'{literal(k)}: {literal(v)}' for k,v in value.items()) + ']'
def mode(value):
    ambient = ', '.join(f'{k}: {literal(v)}' for k,v in value['ambient'].items())
    return f'ThemeMode(tokens: {dictionary(value["tokens"])}, categories: {dictionary(value["categories"])}, ambient: ThemeAmbient({ambient}))'
lines = ['// Generated by scripts/generate_themes.py from docs/themes.json. Do not edit.', 'extension ThemeID {', '  var definition: ThemeDefinition {', '    switch self {']
for theme in data['themes']:
    metadata = ', '.join(f'{k}: {literal(theme[k])}' for k in ('id','name','premium','description','usesSemanticIcons','spacious','clearGlass'))
    lines += [f'    case .{theme["id"]}:', f'      ThemeDefinition({metadata},', f'        light: {mode(theme["light"])},', f'        dark: {mode(theme["dark"])})']
lines += ['    }', '  }', '}']
(ROOT / 'apps/apple/Lakshly/Components/ThemeDefinitions.swift').write_text('\n'.join(lines)+'\n')
